Gjengroing first commit
NINAnor/ecRxiv pull request #28
Opened 2024-09-20 11:07 UTC by idammie

2024-10-01 06:35 UTC, anders-kolstad commented
Hi @idammie , what is the status for the PR? Can I start reviewing it?

2024-10-02 06:31 UTC, idammie commented
> Hi @idammie , what is the status for the PR? Can I start reviewing it?

@anders-kolstad you can start reviewing the PR.

2024-10-02 09:08 UTC, anders-kolstad commented
@idammie , can you please delete some of the unneeded files from the PR? 

- [ ] You have four versions of the qmd file. Assuming NO_GJEN_004 is the correct one, can you please delete the other ones, and rename the correct one NO_GJEN_004. 
- [ ] And same with the htmls. 
- [ ] Please delete 'ecosystemCondition_gjengroing.Rmd' 

You can also make me admin in your repo if you want me to do it for you.

2024-10-02 12:07 UTC, anders-kolstad commented
> @idammie , can you please delete some of the unneeded files from the PR?
> 
> * [ ]  You have four versions of the qmd file. Assuming NO_GJEN_004 is the correct one, can you please delete the other ones, and rename the correct one NO_GJEN_004.
> * [ ]  And same with the htmls.
> * [ ]  Please delete 'ecosystemCondition_gjengroing.Rmd'
> 
> You can also make me admin in your repo if you want me to do it for you.

Actuall, hang on a bit @idammie. I will fork your fork and make some edits there. I will assume NO_GJEN_004 is the one to keep.

2024-10-07 20:32 UTC, anders-kolstad requested changes
Hi. Thank you @idammie. I have finished reviewing the PR. Instead of making comments for on stuff to fix, I tried to suggest as many things as possible directly in a [PR to your fork.](https://github.com/idammie/ecRxiv_gjengroing/pull/1). Please review that PR and merge it to idammie:gjengroing if you  find it OK. This will automatically update your PR to ecRxiv. See for example the diff file [here](https://github.com/idammie/ecRxiv_gjengroing/pull/1/files#diff-5bb9d3370286a69798e985a7df71ed105fba9e8c5947dae9bea9430006db0419). 

I also added some suggestions for improvement beyond what I could do in the review, esp:

1. using indicator values to describe the uncertainty
2. using *rask suksesjon* instead of *tilstand*
3. validating by plotting indicator values against *rask susesjon* across all NiN polygons.

Se details for these issues inside the review.
[Here ](http://htmlpreview.github.io/?https://github.com/NINAnor/ecRxiv_gjengroing_review/blob/review_ALK/indicators/NO_GJEN/R/NO_GJEN_001.html)you can also see what my reviewed version looks like when rendered.

Thanks for submitting and dont hessitat to ask if anything is unclear and I can try to explain better. 

Cheers.

2024-10-07 20:32 UTC, anders-kolstad commented on indicators/NO_GJEN/R/NO_GJEN_004.qmd
> +The NiN polygons including "Våtmark", "Naturlig åpne områder under skoggrensa" and "Semi-naturlig mark" with good ecological condition are used to define a reference gjengroing state. We use the aggr
I think it is best to use the variation in the estimated indicator values to describe the regional uncertainty. This is more aligned with the ecosystem condition framework, bith the Norwegian Fagsystem and the SEEA EA

2024-10-07 20:32 UTC, anders-kolstad commented on indicators/NO_GJEN/R/NO_GJEN_004.qmd
> +The vegetation height percentiles are then scaled to between 0 and 1 using a sigmoid transformation [Oliver at al. (2021)](https://www.sciencedirect.com/science/article/pii/S1470160X21000066).
Please add a little more reasoning why so, and why not say an expoential transformation as suggested here: https://github.com/NINAnor/ecosystemCondition/issues/156

2024-10-07 20:32 UTC, anders-kolstad commented on indicators/NO_GJEN/R/NO_GJEN_004.qmd
> +### 9.1 Scaled indicator values at polygon level
I added two more figures in this section. Please have a look and see if they make sense.

2024-10-21 10:32 UTC, merged