First draft of pollinator indicators
NINAnor/ecRxiv pull request #34
Opened 2024-10-15 11:50 UTC by Peprah94

This is the first draft of the pollinator indicator project. I still have a few things to add to the write-up.

2024-10-23 04:38 UTC, anders-kolstad requested changes
Hi @Peprah94 , I cant render do to one missing RData file. Can you have a look and see if you can locate it?

2024-10-23 04:38 UTC, anders-kolstad commented on indicators/pollinatorIndicators/R/pollinatorIndicators.qmd
> +  load("../data/ecosystemConditions.RData")
This file does not exist.

2024-10-24 12:47 UTC, anders-kolstad commented on indicators/pollinatorIndicators/R/pollinatorIndicators.qmd
> +  load("../data/ecosystemConditions.RData")
Look here: P:\412421_okologisk_tilstand_2024\pollinatorIndicators\oldScripts\Data\markdownResults\image

2024-10-28 12:14 UTC, anders-kolstad requested changes
Thank you @Peprah94 for this PR. The work is very nice. I made direct suggestion in a PR to Peprah:main that you can see [here](https://github.com/Peprah94/ecRxiv/pull/1). I suggest merging this to your main.
The following issues shold be a adressed before moving to the next phase of the review.

1. See comment about concoluted logic using plant ISDMs.
2. Normalisation of Simposon diversity values to create (normative) indicator values

2024-11-01 14:02 UTC, anders-kolstad commented
## ASO-data
There should be around 500 ASO meadows with full transect analyses. The data now only contains about 50. Important data are missing.

2024-11-26 06:11 UTC, Peprah94 commented
> ## ASO-data
> There should be around 500 ASO meadows with full transect analyses. The data now only contains about 50. Important data are missing.

The data we pulled are from GBIF, and the metadata information is formatted. If there are 500 locations, do these 500 locations all contain the data we are interested in? If not, it might not feature in the data. I have done the data format for the ASO meadows like four times.

2024-11-26 06:12 UTC, Peprah94 commented on indicators/pollinatorIndicators/R/pollinatorIndicators.qmd
> +to look at the estimates in the ASO Data meadows by using their values as the reference
These are the bits and pieces the other co-authors can help with.

2024-11-27 07:08 UTC, anders-kolstad approved these changes
gg() was switched to geom_sf()

2024-11-27 07:08 UTC, merged